<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Aashu-PC" ignored="0" name="TC_Login_001" tests="8" failures="7" timestamp="17 Jul 2020 08:04:40 GMT" time="108.887" errors="0">
  <testcase name="login" time="9.76" classname="com.jcp.testcases.TC_Login_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.jcp.testcases.TC_Login_001.login(TC_Login_001.java:53)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="loginDDT" time="15.028" classname="com.jcp.testcases.TC_Login_DDT"/>
  <testcase name="loginDDT" time="14.944" classname="com.jcp.testcases.TC_Login_DDT">
    <failure type="java.lang.AssertionError" message="Login credentials are not valid">
      <![CDATA[java.lang.AssertionError: Login credentials are not valid
at com.jcp.testcases.TC_Login_DDT.loginDDT(TC_Login_DDT.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="10.224" classname="com.jcp.testcases.TC_Login_DDT">
    <failure type="java.lang.AssertionError" message="Login credentials are not valid">
      <![CDATA[java.lang.AssertionError: Login credentials are not valid
at com.jcp.testcases.TC_Login_DDT.loginDDT(TC_Login_DDT.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="10.158" classname="com.jcp.testcases.TC_Login_DDT">
    <failure type="java.lang.AssertionError" message="Login credentials are not valid">
      <![CDATA[java.lang.AssertionError: Login credentials are not valid
at com.jcp.testcases.TC_Login_DDT.loginDDT(TC_Login_DDT.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="9.221" classname="com.jcp.testcases.TC_Login_DDT">
    <failure type="java.lang.AssertionError" message="Login credentials are not valid">
      <![CDATA[java.lang.AssertionError: Login credentials are not valid
at com.jcp.testcases.TC_Login_DDT.loginDDT(TC_Login_DDT.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="9.404" classname="com.jcp.testcases.TC_Login_DDT">
    <failure type="java.lang.AssertionError" message="Login credentials are not valid">
      <![CDATA[java.lang.AssertionError: Login credentials are not valid
at com.jcp.testcases.TC_Login_DDT.loginDDT(TC_Login_DDT.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="9.796" classname="com.jcp.testcases.TC_Login_DDT">
    <failure type="java.lang.AssertionError" message="Login credentials are not valid">
      <![CDATA[java.lang.AssertionError: Login credentials are not valid
at com.jcp.testcases.TC_Login_DDT.loginDDT(TC_Login_DDT.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- TC_Login_001 -->
